#!/usr/bin/env bash
set -euo pipefail
REMOTE_URL=$(git remote get-url origin)
REST=${REMOTE_URL##git@github.com:}
REPO=${REST%%.git}
REF=${1:-'HEAD'}
HASH=$(git rev-parse "$REF")

echo -n "https://github.com/$REPO/commit/$HASH" | pbcopy
echo "Commit link copied to clipboard"
